export const keys = {
  en: [
    { key: '`', code: '`', additionalSymbol: '~' },
    { key: '1', code: 'Digit1', additionalSymbol: '!' },
    { key: '2', code: 'Digit2', additionalSymbol: '@' },
    { key: '3', code: 'Digit3', additionalSymbol: '#' },
    { key: '4', code: 'Digit4', additionalSymbol: '$' },
    { key: '5', code: 'Digit5', additionalSymbol: '%' },
    { key: '6', code: 'Digit6', additionalSymbol: '^' },
    { key: '7', code: 'Digit7', additionalSymbol: '&' },
    { key: '8', code: 'Digit8', additionalSymbol: '*' },
    { key: '9', code: 'Digit9', additionalSymbol: '(' },
    { key: '0', code: 'Digit0', additionalSymbol: ')' },
    { key: '-', code: 'Minus', additionalSymbol: '_' },
    { key: '=', code: 'Equal', additionalSymbol: '+' },
    {
      key: 'Backspace',
      code: 'Backspace',
      additionalSymbol: null,
      breakRow: true,
      className: 'large',
    },
    { key: 'Tab', code: 'Tab', additionalSymbol: null, className: 'small' },
    { key: 'Q', code: 'KeyQ', additionalSymbol: null },
    { key: 'W', code: 'KeyW', additionalSymbol: null },
    { key: 'E', code: 'KeyE', additionalSymbol: null },
    { key: 'R', code: 'KeyR', additionalSymbol: null },
    { key: 'T', code: 'KeyT', additionalSymbol: null },
    { key: 'Y', code: 'KeyY', additionalSymbol: null },
    { key: 'U', code: 'KeyU', additionalSymbol: null },
    { key: 'I', code: 'KeyI', additionalSymbol: null },
    { key: 'O', code: 'KeyO', additionalSymbol: null },
    { key: 'P', code: 'KeyP', additionalSymbol: null },
    { key: '[', code: 'BracketLeft', additionalSymbol: null },
    { key: ']', code: 'BracketRight', additionalSymbol: null },
    {
      key: '\\',
      code: 'Backslash',
      additionalSymbol: '|',
      breakRow: true,
      className: 'small',
    },
    {
      key: 'CapsLock',
      code: 'CapsLock',
      additionalSymbol: null,
      className: 'medium',
    },
    { key: 'A', code: 'KeyA', additionalSymbol: null },
    { key: 'S', code: 'KeyS', additionalSymbol: null },
    { key: 'D', code: 'KeyD', additionalSymbol: null },
    { key: 'F', code: 'KeyF', additionalSymbol: null },
    { key: 'G', code: 'KeyG', additionalSymbol: null },
    { key: 'H', code: 'KeyH', additionalSymbol: null },
    { key: 'J', code: 'KeyJ', additionalSymbol: null },
    { key: 'K', code: 'KeyK', additionalSymbol: null },
    { key: 'L', code: 'KeyL', additionalSymbol: null },
    { key: ';', code: 'Semicolon', additionalSymbol: ':' },
    { key: '\'', code: 'Backslash', additionalSymbol: '"' },
    {
      key: 'Enter',
      code: 'Enter',
      additionalSymbol: null,
      breakRow: true,
      className: 'medium',
    },
    {
      key: 'Shift',
      code: 'ShiftLeft',
      additionalSymbol: null,
      className: 'medium',
    },
    { key: 'Z', code: 'KeyZ', additionalSymbol: null },
    { key: 'X', code: 'KeyX', additionalSymbol: null },
    { key: 'C', code: 'KeyC', additionalSymbol: null },
    { key: 'V', code: 'KeyV', additionalSymbol: null },
    { key: 'B', code: 'KeyB', additionalSymbol: null },
    { key: 'N', code: 'KeyN', additionalSymbol: null },
    { key: 'M', code: 'KeyM', additionalSymbol: null },
    { key: ',', code: 'Comma', additionalSymbol: '<' },
    { key: '.', code: 'Period', additionalSymbol: '>' },
    { key: '/', code: 'Slash', additionalSymbol: '?' },
    { key: '↑', code: 'ArrowUp', additionalSymbol: null },
    {
      key: 'Shift',
      code: 'ShiftRight',
      additionalSymbol: null,
      breakRow: true,
      className: 'large',
    },
    { key: 'Ctrl', code: 'ControlLeft', additionalSymbol: null },
    { key: 'Win', code: 'MetaLeft', additionalSymbol: null },
    { key: 'Alt', code: 'AltLeft', additionalSymbol: null },
    { key: 'Space', code: 'Space', additionalSymbol: null, className: 'huge' },
    { key: 'Alt', code: 'AltRight', additionalSymbol: null },
    { key: 'Ctrl', code: 'ControlRight', additionalSymbol: null },
    { key: '←', code: 'ArrowLeft', additionalSymbol: null },
    { key: '↓', code: 'ArrowDown', additionalSymbol: null },
    { key: '→', code: 'ArrowRight', additionalSymbol: null, breakRow: true },
  ],
  ru: [
    { key: 'ё', code: 'Backquote', additionalSymbol: 'Ё' },
    { key: '1', code: 'Digit1', additionalSymbol: '!' },
    { key: '2', code: 'Digit2', additionalSymbol: '"' },
    { key: '3', code: 'Digit3', additionalSymbol: '№' },
    { key: '4', code: 'Digit4', additionalSymbol: ';' },
    { key: '5', code: 'Digit5', additionalSymbol: '%' },
    { key: '6', code: 'Digit6', additionalSymbol: ':' },
    { key: '7', code: 'Digit7', additionalSymbol: '?' },
    { key: '8', code: 'Digit8', additionalSymbol: '*' },
    { key: '9', code: 'Digit9', additionalSymbol: '(' },
    { key: '0', code: 'Digit0', additionalSymbol: ')' },
    { key: '-', code: 'Minus', additionalSymbol: '_' },
    { key: '=', code: 'Equal', additionalSymbol: '+' },
    {
      key: 'Backspace',
      code: 'Backspace',
      additionalSymbol: null,
      breakRow: true,
      className: 'large',
    },
    { key: 'Tab', code: 'Tab', additionalSymbol: null, className: 'small' },
    { key: 'Й', code: 'KeyQ', additionalSymbol: null },
    { key: 'Ц', code: 'KeyW', additionalSymbol: null },
    { key: 'У', code: 'KeyE', additionalSymbol: null },
    { key: 'К', code: 'KeyR', additionalSymbol: null },
    { key: 'Е', code: 'KeyT', additionalSymbol: null },
    { key: 'Н', code: 'KeyY', additionalSymbol: null },
    { key: 'Г', code: 'KeyU', additionalSymbol: null },
    { key: 'Ш', code: 'KeyI', additionalSymbol: null },
    { key: 'Щ', code: 'KeyO', additionalSymbol: null },
    { key: 'З', code: 'KeyP', additionalSymbol: null },
    { key: 'Х', code: 'BracketLeft', additionalSymbol: null },
    { key: 'Ъ', code: 'BracketRight', additionalSymbol: null },
    {
      key: '\\',
      code: 'Backslash',
      additionalSymbol: '|',
      breakRow: true,
      className: 'small',
    },
    {
      key: 'CapsLock',
      code: 'CapsLock',
      additionalSymbol: null,
      className: 'medium',
    },
    { key: 'Ф', code: 'KeyA', additionalSymbol: null },
    { key: 'Ы', code: 'KeyS', additionalSymbol: null },
    { key: 'В', code: 'KeyD', additionalSymbol: null },
    { key: 'А', code: 'KeyF', additionalSymbol: null },
    { key: 'П', code: 'KeyG', additionalSymbol: null },
    { key: 'Р', code: 'KeyH', additionalSymbol: null },
    { key: 'О', code: 'KeyJ', additionalSymbol: null },
    { key: 'Л', code: 'KeyK', additionalSymbol: null },
    { key: 'Д', code: 'KeyL', additionalSymbol: null },
    { key: 'Ж', code: 'Semicolon', additionalSymbol: null },
    { key: 'Э', code: 'Quote', additionalSymbol: null },
    {
      key: 'Enter',
      code: 'Enter',
      additionalSymbol: null,
      breakRow: true,
      className: 'medium',
    },
    {
      key: 'Shift',
      code: 'ShiftLeft',
      additionalSymbol: null,
      className: 'medium',
    },
    { key: 'я', code: 'KeyZ', additionalSymbol: null },
    { key: 'ч', code: 'KeyX', additionalSymbol: null },
    { key: 'с', code: 'KeyC', additionalSymbol: null },
    { key: 'м', code: 'KeyV', additionalSymbol: null },
    { key: 'и', code: 'KeyB', additionalSymbol: null },
    { key: 'т', code: 'KeyN', additionalSymbol: null },
    { key: 'ь', code: 'KeyM', additionalSymbol: null },
    { key: 'б', code: 'Comma', additionalSymbol: null },
    { key: 'ю', code: 'Period', additionalSymbol: null },
    { key: '.', code: 'Slash', additionalSymbol: ',' },
    { key: '↑', code: 'ArrowUp', additionalSymbol: null },
    {
      key: 'Shift',
      code: 'ShiftRight',
      additionalSymbol: null,
      breakRow: true,
      className: 'large',
    },
    { key: 'Ctrl', code: 'ControlLeft', additionalSymbol: null },
    { key: 'Win', code: 'MetaLeft', additionalSymbol: null },
    { key: 'Alt', code: 'AltLeft', additionalSymbol: null },
    { key: 'Space', code: 'Space', additionalSymbol: null, className: 'huge' },
    { key: 'Alt', code: 'AltRight', additionalSymbol: null },
    { key: 'Ctrl', code: 'ControlRight', additionalSymbol: null },
    { key: '←', code: 'ArrowLeft', additionalSymbol: null },
    { key: '↓', code: 'ArrowDown', additionalSymbol: null },
    { key: '→', code: 'ArrowRight', additionalSymbol: null, breakRow: true },
  ],
};
